dist: xenial
notifications:
  email: false
language: node_js
node_js:
  - "10"
cache: npm
jobs:
  include:
    - stage: Test
      script: npm test
    - stage: npm release
      if: branch = master AND type != pull_request
      node_js: "10"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
    - develop