apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snyk-docker-pull
  annotations:
    github.com/project-slug: snyk/snyk-docker-pull
    github.com/team-slug: snyk/test-enrichment
spec:
  type: internal-library
  lifecycle: "-"
  owner: test-enrichment
