apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snyk-docker-pull
  annotations:
    github.com/project-slug: snyk/snyk-docker-pull
    github.com/team-slug: snyk/container-integration
spec:
  type: internal-library
  lifecycle: "-"
  owner: container-integration
